### ISSUE TITLE
Sobre la licencia del libro

### ISSUE THREAD

**Issue by theraot** [FedeHC/SICP-ES#2]
CC BY-SA 4.0 es una licencia atributiva. Dice [Atribución-CompartirIgual 4.0 Internacional (CC BY-SA 4.0)](https://creativecommons.org/licenses/by-sa/4.0/deed.es):

> Atribución — Usted debe dar crédito de manera adecuada, brindar un enlace a la licencia, e indicar si se han realizado cambios. Puede hacerlo en cualquier forma razonable, pero no de forma tal que sugiera que usted o su uso tienen el apoyo de la licenciante.

Debido a esto considero que se debería mantener la atribución a los autores en [la linea 17 de la contraportada](https://github.com/FedeHC/SICP-ES/blame/master/secciones/02-contraportada.md#L17), e incluso, tal vez, agregar la atribución de la traducción.

Ejemplo:

> Esta traducción realizada por FedeHC del libro Estructura e Interpretación de Programas Informáticos por Harold Abelson y Gerald Jay Sussman con Julie Sussman está publicada bajo la licencia internacional Creative Commons Atribución-CompartirIgual 4.0 Internacional (CC BY-SA 4.0)

De forma similar en [README.md](https://github.com/FedeHC/SICP-ES/blame/master/README.md#L18)

De paso considera si aceptaras contribuciones a la traducción, y que significa eso respecto a atribución en la licencia.

Una alternativa a listar cada persona que contribuya, puede ser la creación de un seudónimo colectivo, y mantener la lista un archivo separado.

**Comment by fedehc** [comment]
Nuevamente, perdón por la tardia respuesta.

Pero el nombre de los autores figura inmediatamente debajo en la misma contraportada (ni hablar en README). Realmente me parece redundante aclararlo.
